version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: goal-tracker-db
    environment:
      POSTGRES_DB: goaltracker
      POSTGRES_USER: goaltracker_user
      POSTGRES_PASSWORD: goaltracker_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
