services:
  # PostgreSQL Database
  - type: postgresql
    name: goal-tracker-db
    plan: free
    ipAllowList: []

  # Web Service
  - type: web
    name: goal-tracker-app
    env: docker
    plan: free
    region: oregon
    healthCheckPath: /
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: goal-tracker-db
          property: connectionString
      - key: DB_USERNAME
        fromDatabase:
          name: goal-tracker-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: goal-tracker-db
          property: password
    buildCommand: docker build -t goal-tracker .
    startCommand: docker run -p $PORT:8080 goal-tracker
